version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.11

    working_directory: /go/src/github.com/work/go-web-server
    steps:
      - checkout

      - run: go get -v -t -d ./...
      - run: go test -v ./...